"""empty message

Revision ID: 357aaabb50e5
Revises: 83054d586a94
Create Date: 2024-03-25 18:31:55.439515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357aaabb50e5'
down_revision = '83054d586a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_index('ix_cart_item_id')
        batch_op.create_index(batch_op.f('ix_cart_item_id'), ['item_id'], unique=False)
        batch_op.drop_index('ix_cart_user_id')
        batch_op.create_index(batch_op.f('ix_cart_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cart_user_id'))
        batch_op.create_index('ix_cart_user_id', ['user_id'], unique=1)
        batch_op.drop_index(batch_op.f('ix_cart_item_id'))
        batch_op.create_index('ix_cart_item_id', ['item_id'], unique=1)

    # ### end Alembic commands ###
